version: "3.8"

services:
  db:
    image: postgres:15
    container_name: myapp_db
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .   # ðŸ‘ˆ usa o Dockerfile da raiz
    container_name: myapp
    working_dir: /app
    volumes:
      - ./:/app
      - gradle_cache:/home/gradle/.gradle
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/mydb
      SPRING_DATASOURCE_USERNAME: myuser
      SPRING_DATASOURCE_PASSWORD: mypassword
    command: >
      sh -c "
        until pg_isready -h db -p 5432; do
          echo 'Waiting for database...'
          sleep 2
        done
        ./gradlew bootRun
      "

volumes:
  pgdata:
  gradle_cache:
